# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ReactiveCocoaDemo' do
pod 'ReactiveCocoa', '~> 2.4.2'
pod 'AFNetworking', '~> 2.5.0'
pod 'MBProgressHUD', '~> 0.9'
end

target 'ReactiveCocoaDemoTests' do
pod 'ReactiveCocoa', '~> 2.4.2'
pod 'AFNetworking', '~> 2.5.0'
pod 'MBProgressHUD', '~> 0.9'
end

