# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '图片压缩' do
pod 'ZipArchive', '~> 1.4.0'
end

target '图片压缩UITests' do

end

