# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'iOS唯一标示符' do
pod 'SSKeychain','~1.2.3'
end

target 'iOS唯一标示符Tests' do

end

target 'iOS唯一标示符UITests' do

end

