# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '获取当前设备内存以及自定义相册' do
pod 'SystemServices', '~> 1.0.2'
end

